/**
 * reminderStore.ts — Zustand store for Calendar & Reminders
 * Manages user-created reminders + auto-generated PPS well-baby + Garantisadong Pambata
 */

import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { zustandStorage } from './storage';



export type ReminderCategory =
  | 'vaccine' | 'checkup' | 'feeding' | 'sleep'
  | 'medication' | 'vitamins' | 'gp' | 'custom';

export type RepeatType = 'none' | 'daily' | 'weekly' | 'monthly';

export interface Reminder {
  id: string;
  childId: string;
  title: string;
  category: ReminderCategory;
  scheduledAt: string; // "YYYY-MM-DDTHH:mm"
  allDay: boolean;
  repeatType: RepeatType;
  notifyMinutesBefore: number; // 0, 15, 30, 60, 1440
  notes: string;
  isActive: boolean;
  isAutoGenerated: boolean;
  autoType?: 'pps' | 'gp';
  createdAt: string;
}

export interface NotificationSettings {
  masterEnabled: boolean;
  vaccineReminders: boolean;
  checkupReminders: boolean;
  feedingReminders: boolean;
  medicationReminders: boolean;
  customReminders: boolean;
  quietHoursEnabled: boolean;
  quietHoursStart: string; // "HH:mm"
  quietHoursEnd: string;   // "HH:mm"
}

// PPS (Philippine Pediatric Society) well-baby schedule — weeks from birthday
export const PPS_SCHEDULE = [
  { weeks: 1,   key: '1-week',   labelEN: '1-week',   labelFIL: '1-linggo',  labelZH: '1周' },
  { weeks: 4,   key: '1-month',  labelEN: '1-month',  labelFIL: '1-buwan',   labelZH: '1个月' },
  { weeks: 9,   key: '2-month',  labelEN: '2-month',  labelFIL: '2-buwan',   labelZH: '2个月' },
  { weeks: 17,  key: '4-month',  labelEN: '4-month',  labelFIL: '4-buwan',   labelZH: '4个月' },
  { weeks: 26,  key: '6-month',  labelEN: '6-month',  labelFIL: '6-buwan',   labelZH: '6个月' },
  { weeks: 39,  key: '9-month',  labelEN: '9-month',  labelFIL: '9-buwan',   labelZH: '9个月' },
  { weeks: 52,  key: '12-month', labelEN: '12-month', labelFIL: '12-buwan',  labelZH: '12个月' },
  { weeks: 65,  key: '15-month', labelEN: '15-month', labelFIL: '15-buwan',  labelZH: '15个月' },
  { weeks: 78,  key: '18-month', labelEN: '18-month', labelFIL: '18-buwan',  labelZH: '18个月' },
  { weeks: 104, key: '24-month', labelEN: '24-month', labelFIL: '24-buwan',  labelZH: '24个月' },
  { weeks: 156, key: '3-year',   labelEN: '3-year',   labelFIL: '3-taon',    labelZH: '3岁' },
  { weeks: 208, key: '4-year',   labelEN: '4-year',   labelFIL: '4-taon',    labelZH: '4岁' },
  { weeks: 260, key: '5-year',   labelEN: '5-year',   labelFIL: '5-taon',    labelZH: '5岁' },
] as const;

function uuid(): string {
  return Math.random().toString(36).substring(2, 9) + Date.now().toString(36);
}

interface ReminderState {
  reminders: Reminder[];
  settings: NotificationSettings;

  addReminder: (r: Omit<Reminder, 'id' | 'createdAt'>) => string;
  updateReminder: (id: string, updates: Partial<Reminder>) => void;
  deleteReminder: (id: string) => void;

  getRemindersForChild: (childId: string) => Reminder[];
  getByDate: (childId: string, dateStr: string) => Reminder[];
  getDatesWithCategories: (childId: string, year: number, month: number) => Map<number, ReminderCategory[]>;
  getUpcoming: (childId: string, days?: number) => Reminder[];

  autoGeneratePPS: (childId: string, birthday: string, nickname: string) => void;
  autoGenerateGP: (childId: string, year: number) => void;

  updateSettings: (updates: Partial<NotificationSettings>) => void;
}

export const useReminderStore = create<ReminderState>()(
  persist(
    (set, get) => ({
      reminders: [],
      settings: {
        masterEnabled: true,
        vaccineReminders: true,
        checkupReminders: true,
        feedingReminders: true,
        medicationReminders: true,
        customReminders: true,
        quietHoursEnabled: false,
        quietHoursStart: '22:00',
        quietHoursEnd: '06:00',
      },

      addReminder: (r) => {
        const id = uuid();
        const newR: Reminder = { ...r, id, createdAt: new Date().toISOString() };
        set(s => ({ reminders: [...s.reminders, newR] }));
        return id;
      },

      updateReminder: (id, updates) => {
        set(s => ({
          reminders: s.reminders.map(r => r.id === id ? { ...r, ...updates } : r),
        }));
      },

      deleteReminder: (id) => {
        set(s => ({ reminders: s.reminders.filter(r => r.id !== id) }));
      },

      getRemindersForChild: (childId) => {
        return get().reminders.filter(r => r.childId === childId && r.isActive);
      },

      getByDate: (childId, dateStr) => {
        return get().reminders.filter(r =>
          r.childId === childId &&
          r.isActive &&
          r.scheduledAt.startsWith(dateStr)
        );
      },

      getDatesWithCategories: (childId, year, month) => {
        const map = new Map<number, ReminderCategory[]>();
        const rs = get().reminders.filter(r => r.childId === childId && r.isActive);
        for (const r of rs) {
          const d = new Date(r.scheduledAt);
          if (d.getFullYear() === year && d.getMonth() === month) {
            const day = d.getDate();
            if (!map.has(day)) map.set(day, []);
            const cats = map.get(day)!;
            if (!cats.includes(r.category)) cats.push(r.category);
          }
        }
        return map;
      },

      getUpcoming: (childId, days = 60) => {
        const now = new Date(); now.setHours(0, 0, 0, 0);
        const end = new Date(now);
        end.setDate(end.getDate() + days);
        return get().reminders
          .filter(r => {
            if (r.childId !== childId || !r.isActive) return false;
            const d = new Date(r.scheduledAt);
            return d >= now && d <= end;
          })
          .sort((a, b) => a.scheduledAt.localeCompare(b.scheduledAt));
      },

      autoGeneratePPS: (childId, birthday, nickname) => {
        const existing = get().reminders.filter(r => r.childId === childId && r.autoType === 'pps');
        if (existing.length > 0) return; // already done

        const bd = new Date(birthday);
        const sevenDaysAgo = new Date();
        sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

        for (const slot of PPS_SCHEDULE) {
          const checkupDate = new Date(bd);
          checkupDate.setDate(checkupDate.getDate() + slot.weeks * 7);
          if (checkupDate < sevenDaysAgo) continue; // skip far past

          // Create reminder 3 days before checkup
          const reminderDate = new Date(checkupDate);
          reminderDate.setDate(reminderDate.getDate() - 3);
          const iso = reminderDate.toISOString().split('T')[0] + 'T09:00';

          get().addReminder({
            childId,
            title: `🏥 ${slot.labelEN} well-baby checkup for ${nickname}`,
            category: 'checkup',
            scheduledAt: iso,
            allDay: false,
            repeatType: 'none',
            notifyMinutesBefore: 1440,
            notes: 'Bring your MCH Booklet (Mother & Child Health Booklet). PPS recommended well-baby visit.',
            isActive: true,
            isAutoGenerated: true,
            autoType: 'pps',
          });
        }
      },

      autoGenerateGP: (childId, year) => {
        const existing = get().reminders.filter(r =>
          r.childId === childId &&
          r.autoType === 'gp' &&
          r.scheduledAt.startsWith(`${year}`)
        );
        if (existing.length >= 2) return;

        // June 15 → July campaign
        get().addReminder({
          childId,
          title: '🌟 Garantisadong Pambata: Coming in July! Free Vitamin A + deworming at BHS',
          category: 'gp',
          scheduledAt: `${year}-06-15T09:00`,
          allDay: true,
          repeatType: 'none',
          notifyMinutesBefore: 0,
          notes: 'Every July: Free Vitamin A + deworming at Barangay Health Station (BHS) for children 6 months to 5 years.',
          isActive: true,
          isAutoGenerated: true,
          autoType: 'gp',
        });

        // December 15 → January campaign
        get().addReminder({
          childId,
          title: '🌟 Garantisadong Pambata: Coming in January! Free Vitamin A + deworming at BHS',
          category: 'gp',
          scheduledAt: `${year}-12-15T09:00`,
          allDay: true,
          repeatType: 'none',
          notifyMinutesBefore: 0,
          notes: 'Every January: Free Vitamin A + deworming at Barangay Health Station (BHS) for children 6 months to 5 years.',
          isActive: true,
          isAutoGenerated: true,
          autoType: 'gp',
        });
      },

      updateSettings: (updates) => {
        set(s => ({ settings: { ...s.settings, ...updates } }));
      },
    }),
    {
      name: 'reminder-store',
      storage: zustandStorage,
    }
  )
);

// Dev access
if (typeof window !== 'undefined') {
  (window as any).__reminderStore = useReminderStore;
}
