-- NEWBORN (0–3 months)
INSERT INTO milestones_reference (age_months_min, age_months_max, category, milestone_text, stage_name, is_who_standard) VALUES
(0, 3, 'motor', 'Lifts head briefly during tummy time', 'Newborn', true),
(0, 3, 'vision', 'Follows moving objects with eyes', 'Newborn', true),
(0, 3, 'hearing', 'Startles at loud sounds', 'Newborn', true),
(0, 3, 'social', 'Recognizes caregiver''s face and voice', 'Newborn', false),
(1, 3, 'social', 'First social smile (6–8 weeks)', 'Newborn', true),
(1, 3, 'language', 'Coos and makes soft vowel sounds', 'Newborn', true),
-- YOUNG INFANT (3–6 months)
(3, 6, 'motor', 'Rolls front to back and back to front', 'Young Infant', true),
(3, 6, 'motor', 'Reaches for and grasps objects', 'Young Infant', true),
(3, 6, 'social', 'Laughs and squeals with delight', 'Young Infant', true),
(4, 6, 'motor', 'Sits with support (tripod position)', 'Young Infant', true),
(3, 6, 'language', 'Babbles: ba, da, ma sounds', 'Young Infant', true),
(4, 6, 'social', 'Recognizes own name when called', 'Young Infant', true),
-- OLDER INFANT (6–12 months)
(6, 9, 'motor', 'Sits independently without support', 'Older Infant', true),
(7, 10, 'motor', 'Crawls on hands and knees', 'Older Infant', true),
(9, 12, 'motor', 'Pulls to stand and cruises along furniture', 'Older Infant', true),
(9, 12, 'language', 'First meaningful words (mama, dada)', 'Older Infant', true),
(9, 12, 'motor', 'Pincer grasp (thumb and index finger)', 'Older Infant', true),
(8, 12, 'social', 'Stranger anxiety begins', 'Older Infant', false),
(9, 12, 'social', 'Waves bye-bye on cue', 'Older Infant', true),
(10, 12, 'feeding', 'Drinks from a cup with help', 'Older Infant', false),
-- TODDLER I (12–18 months)
(12, 15, 'motor', 'Walks independently', 'Toddler I', true),
(12, 18, 'language', 'Uses 5–20 words', 'Toddler I', true),
(12, 18, 'social', 'Points to communicate desires', 'Toddler I', true),
(12, 18, 'motor', 'Stacks 2–3 blocks', 'Toddler I', false),
(15, 18, 'play', 'Shows pretend play (feeds doll)', 'Toddler I', false),
(12, 18, 'cognitive', 'Follows simple one-step instructions', 'Toddler I', true),
-- TODDLER II (18–24 months)
(18, 24, 'motor', 'Runs (though still unsteady)', 'Toddler II', true),
(18, 24, 'language', '50+ words; begins 2-word phrases', 'Toddler II', true),
(18, 24, 'cognitive', 'Follows 2-step instructions', 'Toddler II', true),
(18, 24, 'motor', 'Scribbles with crayon', 'Toddler II', false),
(18, 24, 'motor', 'Kicks and throws a ball', 'Toddler II', false),
(18, 24, 'social', 'Begins showing empathy', 'Toddler II', false),
-- TODDLER III (2–3 years)
(24, 36, 'language', '3+ word sentences; asks why constantly', 'Toddler III', true),
(24, 36, 'self-care', 'Daytime toilet training', 'Toddler III', false),
(24, 36, 'self-care', 'Dresses and undresses with help', 'Toddler III', false),
(24, 36, 'motor', 'Climbs stairs alternating feet', 'Toddler III', true),
(24, 36, 'social', 'Parallel play with other children', 'Toddler III', false),
(24, 36, 'cognitive', 'Names familiar people in photos', 'Toddler III', false),
-- PRESCHOOL (3–5 years)
(36, 60, 'language', 'Complex sentences and questions', 'Preschool', true),
(36, 60, 'motor', 'Draws circles, crosses, and basic faces', 'Preschool', false),
(48, 60, 'motor', 'Hops on one foot', 'Preschool', true),
(36, 60, 'cognitive', 'Understands counting to 10', 'Preschool', false),
(36, 60, 'play', 'Imaginative role play (doctor, chef)', 'Preschool', false),
(48, 60, 'literacy', 'Recognizes letters in own name', 'Preschool', false),
-- SCHOOL AGE I (5–8 years)
(60, 96, 'literacy', 'Reads simple words and short sentences', 'School Age I', false),
(60, 96, 'cognitive', 'Adds and subtracts small numbers', 'School Age I', false),
(72, 96, 'motor', 'Rides a bicycle without training wheels', 'School Age I', false),
(72, 84, 'physical', 'Loses first baby tooth', 'School Age I', false),
(60, 96, 'social', 'Forms strong peer friendships', 'School Age I', false),
(60, 96, 'cognitive', 'Understands rules, fairness, consequences', 'School Age I', false),
-- SCHOOL AGE II (8–10 years)
(96, 120, 'cognitive', 'Multi-step reasoning and problem-solving', 'School Age II', false),
(96, 120, 'literacy', 'Reads chapter books independently', 'School Age II', false),
(96, 120, 'physical', 'Participates in team sports', 'School Age II', false),
(96, 120, 'cognitive', 'Longer attention span for focused tasks', 'School Age II', false),
(96, 120, 'emotional', 'More complex emotional regulation', 'School Age II', false),
-- PRETEEN (10–12 years)
(120, 144, 'physical', 'Early puberty signs begin (vary by child)', 'Preteen', false),
(120, 144, 'cognitive', 'Logical planning and self-organization', 'Preteen', false),
(120, 144, 'social', 'Increasing independence and privacy needs', 'Preteen', false),
(120, 144, 'health', 'HPV vaccine eligibility', 'Preteen', false),
(132, 144, 'health', 'Tdap booster due', 'Preteen', false),
(120, 144, 'social', 'Interest in social identity and peer groups', 'Preteen', false),
(120, 144, 'digital', 'Digital literacy and online safety awareness', 'Preteen', false);
