/**
 * calendar.tsx — Calendar & Reminders (Page 2)
 * BMAD: Beats AsianParents — dynamic month grid, vaccine reminders auto-imported,
 *       PPS well-baby checkups auto-generated, Garantisadong Pambata, AI summary,
 *       Add/Edit modal, notification settings, category filter, trilingual
 */

import React, { useState, useEffect, useMemo } from 'react';
import {
  ScrollView, View, Text, TouchableOpacity, Modal, TextInput,
  StyleSheet, Dimensions, Switch, Alert, Platform, KeyboardAvoidingView,
} from 'react-native';
import { SkeletonList } from '../../components/SkeletonCard';
import { LinearGradient } from 'expo-linear-gradient';
import { useTranslation } from 'react-i18next';

import { Syringe, Hospital, Droplets, Moon, Pill, Leaf, Star, FileText, Clock, Bot, PartyPopper, ClipboardList, Flower2, Calendar as CalendarIcon, CalendarDays } from 'lucide-react-native';

import Colors from '../../constants/Colors';
import { useChildStore, getChildDisplayName } from '../../store/childStore';
import { useReminderStore, Reminder, ReminderCategory, RepeatType } from '../../store/reminderStore';
import { useVaccineStore } from '../../store/vaccineStore';

const { width: W } = Dimensions.get('window');
const PINK  = Colors.primaryPink;  // #E63B6F
const DARK  = Colors.dark;
const GRAY  = Colors.midGray;
const BG    = '#FFF5F8';

// ─── Category config ─────────────────────────────────────────────────────────

const CAT: Record<ReminderCategory, { color: string; bg: string; icon: React.ReactNode }> = {
  vaccine:    { color: Colors.primaryPink, bg: Colors.softPink, icon: <Syringe size={18} strokeWidth={1.5} color={Colors.primaryPink} /> },
  checkup:    { color: Colors.blue, bg: Colors.softBlue, icon: <Hospital size={18} strokeWidth={1.5} color={Colors.blue} /> },
  feeding:    { color: Colors.gold, bg: Colors.softGold, icon: <Droplets size={18} strokeWidth={1.5} color={Colors.gold} /> },
  sleep:      { color: '#8B5CF6', bg: '#F3F0FF', icon: <Moon size={18} strokeWidth={1.5} color={'#8B5CF6'} /> },
  medication: { color: Colors.mint, bg: Colors.softMint, icon: <Pill size={18} strokeWidth={1.5} color={Colors.mint} /> },
  vitamins:   { color: Colors.mint, bg: Colors.softMint, icon: <Leaf size={18} strokeWidth={1.5} color={Colors.mint} /> },
  gp:         { color: Colors.gold, bg: Colors.softGold, icon: <Star size={18} strokeWidth={1.5} color={Colors.gold} /> },
  custom:     { color: Colors.lightGray, bg: '#F5F5F5', icon: <FileText size={18} strokeWidth={1.5} color={Colors.lightGray} /> },
};

const ALL_CATS: ReminderCategory[] = ['vaccine', 'checkup', 'feeding', 'sleep', 'medication', 'vitamins', 'gp', 'custom'];
const DAY_LABELS = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];
const MONTH_NAMES = ['January','February','March','April','May','June','July','August','September','October','November','December'];

// ─── Unified event type (merged from reminderStore + vaccineStore) ────────────

interface CalEvent {
  id: string;
  title: string;
  date: string;      // YYYY-MM-DD
  time?: string;     // HH:MM or undefined if allDay
  category: ReminderCategory;
  allDay: boolean;
  notes?: string;
  source: 'reminder' | 'vaccine';
  reminderId?: string;
  isAutoGenerated?: boolean;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function fmtDatePH(iso: string): string {
  if (!iso) return '—';
  const d = new Date(iso + (iso.length === 10 ? 'T00:00' : ''));
  return d.toLocaleDateString('en-PH', { month: 'short', day: 'numeric', year: 'numeric' });
}

function fmtTime(hhmm: string): string {
  if (!hhmm) return '';
  const [h, m] = hhmm.split(':').map(Number);
  const ampm = h >= 12 ? 'PM' : 'AM';
  const hh = h % 12 || 12;
  return `${hh}:${String(m).padStart(2, '0')} ${ampm}`;
}

function toDateStr(y: number, m: number, d: number): string {
  return `${y}-${String(m + 1).padStart(2, '0')}-${String(d).padStart(2, '0')}`;
}

function todayStr(): string {
  return new Date().toISOString().split('T')[0];
}

function relativeDayLabel(dateStr: string, t: (k: string, o?: object) => string): string {
  const today = todayStr();
  const d = new Date();
  d.setDate(d.getDate() + 1);
  const tom = d.toISOString().split('T')[0];
  if (dateStr === today) return t('calendar.today');
  if (dateStr === tom)   return t('calendar.tomorrow');
  const diff = Math.round((new Date(dateStr).getTime() - new Date(today).getTime()) / 86400000);
  if (diff > 0) return t('calendar.in_x_days', { days: diff });
  return fmtDatePH(dateStr);
}

// ─── Category Legend ──────────────────────────────────────────────────────────

function CategoryLegend({ t }: { t: (k: string) => string }) {
  return (
    <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ marginBottom: 12 }}>
      <View style={{ flexDirection: 'row', gap: 8, paddingHorizontal: 2, paddingBottom: 4 }}>
        {ALL_CATS.map(cat => (
          <View key={cat} style={[leg.chip, { backgroundColor: CAT[cat].bg, borderColor: CAT[cat].color + '44' }]}>
            {CAT[cat].icon}
            <Text style={[leg.label, { color: CAT[cat].color }]}>{t(`calendar.${cat}`)}</Text>
          </View>
        ))}
      </View>
    </ScrollView>
  );
}

const leg = StyleSheet.create({
  chip:  { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 12, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1 },
  label: { fontSize: 11, fontWeight: '700' },
});

// ─── Event Dots for a calendar cell ───────────────────────────────────────────

function EventDots({ cats }: { cats: ReminderCategory[] }) {
  const shown = cats.slice(0, 3);
  return (
    <View style={{ flexDirection: 'row', gap: 2, marginTop: 2, justifyContent: 'center' }}>
      {shown.map((cat, i) => (
        <View key={i} style={{ width: 5, height: 5, borderRadius: 3, backgroundColor: CAT[cat].color }} />
      ))}
    </View>
  );
}

// ─── Monthly Calendar Grid ────────────────────────────────────────────────────

interface MonthGridProps {
  year: number; month: number;
  selectedDay: number | null;
  onDayPress: (day: number) => void;
  dotMap: Map<number, ReminderCategory[]>;
  onPrev: () => void; onNext: () => void;
}

function MonthGrid({ year, month, selectedDay, onDayPress, dotMap, onPrev, onNext }: MonthGridProps) {
  const today       = new Date();
  const todayY      = today.getFullYear();
  const todayM      = today.getMonth();
  const todayD      = today.getDate();

  const daysInMonth   = new Date(year, month + 1, 0).getDate();
  const firstWeekday  = new Date(year, month, 1).getDay(); // 0=Sun
  const totalCells    = Math.ceil((daysInMonth + firstWeekday) / 7) * 7;

  return (
    <View style={mg.card}>
      {/* Month navigator */}
      <View style={mg.navRow}>
        <TouchableOpacity onPress={onPrev} style={mg.navBtn} activeOpacity={0.7}>
          <Text style={mg.navArrow}>‹</Text>
        </TouchableOpacity>
        <Text style={mg.monthLabel}>{MONTH_NAMES[month]} {year}</Text>
        <TouchableOpacity onPress={onNext} style={mg.navBtn} activeOpacity={0.7}>
          <Text style={mg.navArrow}>›</Text>
        </TouchableOpacity>
      </View>

      {/* Day header */}
      <View style={mg.dayHeaderRow}>
        {DAY_LABELS.map((d, i) => (
          <Text key={i} style={[mg.dayHeader, (i === 0 || i === 6) ? { color: PINK + 'CC' } : {}]}>{d}</Text>
        ))}
      </View>

      {/* Grid */}
      <View style={mg.grid}>
        {Array.from({ length: totalCells }, (_, i) => {
          const dayNum = i - firstWeekday + 1;
          const isCurrentMonth = dayNum >= 1 && dayNum <= daysInMonth;
          const isToday  = isCurrentMonth && year === todayY && month === todayM && dayNum === todayD;
          const isSelect = isCurrentMonth && dayNum === selectedDay;
          const cats     = isCurrentMonth ? (dotMap.get(dayNum) ?? []) : [];

          return (
            <TouchableOpacity
              key={i}
              style={[mg.cell, isToday && mg.cellToday, isSelect && mg.cellSelected]}
              onPress={() => { if (isCurrentMonth) onDayPress(dayNum); }}
              activeOpacity={isCurrentMonth ? 0.7 : 1}
            >
              <Text style={[
                mg.cellNum,
                !isCurrentMonth && mg.cellNumFaded,
                isToday  && mg.cellNumToday,
                isSelect && mg.cellNumSelected,
              ]}>
                {isCurrentMonth ? dayNum : ''}
              </Text>
              {cats.length > 0 && <EventDots cats={cats} />}
            </TouchableOpacity>
          );
        })}
      </View>
    </View>
  );
}

const mg = StyleSheet.create({
  card:           { backgroundColor: Colors.white, borderRadius: 22, padding: 16, marginBottom: 16, shadowColor: PINK, shadowOpacity: 0.1, shadowRadius: 12, elevation: 4, borderWidth: 1, borderColor: '#FCE4EC' },
  navRow:         { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  navBtn:         { width: 36, height: 36, borderRadius: 18, backgroundColor: Colors.softPink, alignItems: 'center', justifyContent: 'center' },
  navArrow:       { fontSize: 22, color: PINK, fontWeight: '800', lineHeight: 26 },
  monthLabel:     { fontSize: 17, fontWeight: '800', color: DARK },
  dayHeaderRow:   { flexDirection: 'row', marginBottom: 4 },
  dayHeader:      { width: `${100/7}%`, textAlign: 'center', fontSize: 11, fontWeight: '700', color: GRAY, paddingBottom: 4 },
  grid:           { flexDirection: 'row', flexWrap: 'wrap' },
  cell:           { width: `${100/7}%`, aspectRatio: 1, alignItems: 'center', justifyContent: 'center', borderRadius: 12 },
  cellNum:        { fontSize: 13, color: DARK, fontWeight: '500' },
  cellNumFaded:   { color: '#DDD' },
  cellToday:      { backgroundColor: Colors.softPink },
  cellNumToday:   { color: PINK, fontWeight: '800' },
  cellSelected:   { backgroundColor: PINK },
  cellNumSelected:{ color: Colors.white, fontWeight: '800' },
});

// ─── Single Event Card ────────────────────────────────────────────────────────

function EventCard({ ev, onPress }: { ev: CalEvent; onPress: () => void }) {
  const cfg = CAT[ev.category];
  return (
    <TouchableOpacity style={[ec.row, { borderLeftColor: cfg.color }]} onPress={onPress} activeOpacity={0.8}>
      <View style={[ec.iconWrap, { backgroundColor: cfg.bg }]}>
        {cfg.icon}
      </View>
      <View style={ec.info}>
        <Text style={ec.title} numberOfLines={2}>{ev.title}</Text>
        <View style={{ flexDirection: 'row', alignItems: 'center', gap: 4 }}>
          {(ev.allDay || ev.time) && <Clock size={12} strokeWidth={1.5} color={GRAY} />}
          <Text style={ec.sub}>
            {ev.allDay ? 'All day' : (ev.time ? fmtTime(ev.time) : '')}
          </Text>
          {ev.isAutoGenerated && <Bot size={12} strokeWidth={1.5} color={GRAY} />}
        </View>
        {ev.notes ? <Text style={ec.notes} numberOfLines={1}>{ev.notes}</Text> : null}
      </View>
      {ev.source === 'reminder' &&
        <Text style={ec.chevron}>›</Text>
      }
    </TouchableOpacity>
  );
}

const ec = StyleSheet.create({
  row:     { flexDirection: 'row', alignItems: 'center', backgroundColor: Colors.white, borderRadius: 14, padding: 12, marginBottom: 8, borderLeftWidth: 4, shadowColor: '#000', shadowOpacity: 0.04, shadowRadius: 6, elevation: 2 },
  iconWrap:{ width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  info:    { flex: 1 },
  title:   { fontSize: 13, fontWeight: '700', color: DARK, marginBottom: 2 },
  sub:     { fontSize: 11, color: GRAY },
  notes:   { fontSize: 11, color: Colors.lightGray, marginTop: 2 },
  chevron: { fontSize: 20, color: '#DDD', marginLeft: 8 },
});

// ─── Weekly Summary Bar ───────────────────────────────────────────────────────

function WeeklySummaryBar({ events, t }: { events: CalEvent[]; t: (k: string, o?: object) => string }) {
  const today   = new Date(); today.setHours(0,0,0,0);
  const weekEnd = new Date(today); weekEnd.setDate(weekEnd.getDate() + 7);
  const thisWeek = events.filter(e => {
    const d = new Date(e.date); return d >= today && d < weekEnd;
  });
  const msg  = thisWeek.length === 0
    ? t('calendar.summary_all_clear')
    : t('calendar.summary_events_week', { count: thisWeek.length });
  const nextEv = thisWeek[0];
  return (
    <LinearGradient colors={[Colors.softPink, '#FFF5F8']} style={ws.bar} start={{ x: 0, y: 0 }} end={{ x: 1, y: 0 }}>
      {thisWeek.length === 0
        ? <PartyPopper size={22} strokeWidth={1.5} color={Colors.gold} />
        : <ClipboardList size={22} strokeWidth={1.5} color={PINK} />
      }
      <View style={{ flex: 1 }}>
        <Text style={ws.msg}>{msg}</Text>
        {nextEv && (
          <Text style={ws.next} numberOfLines={1}>{t('calendar.summary_next', { title: nextEv.title })}</Text>
        )}
      </View>
    </LinearGradient>
  );
}

const ws = StyleSheet.create({
  bar:  { flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 16, padding: 14, marginBottom: 16 },
  msg:  { fontSize: 13, fontWeight: '700', color: DARK },
  next: { fontSize: 11, color: GRAY, marginTop: 2 },
});

// ─── Add/Edit Reminder Modal ──────────────────────────────────────────────────

const REPEAT_OPTS: { key: RepeatType; i18n: string }[] = [
  { key: 'none',    i18n: 'calendar.repeat_none' },
  { key: 'daily',   i18n: 'calendar.repeat_daily' },
  { key: 'weekly',  i18n: 'calendar.repeat_weekly' },
  { key: 'monthly', i18n: 'calendar.repeat_monthly' },
];
const NOTIFY_OPTS: { val: number; i18n: string }[] = [
  { val: 0,    i18n: 'calendar.notify_at_time' },
  { val: 15,   i18n: 'calendar.notify_15min' },
  { val: 30,   i18n: 'calendar.notify_30min' },
  { val: 60,   i18n: 'calendar.notify_1hour' },
  { val: 1440, i18n: 'calendar.notify_1day' },
];

interface ReminderForm {
  title: string; category: ReminderCategory;
  date: string;  time: string;  allDay: boolean;
  repeatType: RepeatType; notifyMinutesBefore: number; notes: string;
}
const BLANK_FORM: ReminderForm = {
  title: '', category: 'custom', date: todayStr(),
  time: '09:00', allDay: false, repeatType: 'none',
  notifyMinutesBefore: 15, notes: '',
};

interface ReminderModalProps {
  visible: boolean; editing: Reminder | null;
  childId: string; presetDate?: string;
  onClose: () => void;
  onSave: (form: ReminderForm) => void;
  onDelete: (id: string) => void;
  t: (k: string, o?: object) => string;
}

function ReminderModal({ visible, editing, presetDate, onClose, onSave, onDelete, t }: ReminderModalProps) {
  const [form, setForm] = useState<ReminderForm>(BLANK_FORM);
  const upd = (k: keyof ReminderForm) => (v: any) => setForm(f => ({ ...f, [k]: v }));

  useEffect(() => {
    if (!visible) return;
    if (editing) {
      setForm({
        title: editing.title, category: editing.category,
        date: editing.scheduledAt.split('T')[0],
        time: editing.scheduledAt.split('T')[1]?.substring(0, 5) ?? '09:00',
        allDay: editing.allDay, repeatType: editing.repeatType,
        notifyMinutesBefore: editing.notifyMinutesBefore, notes: editing.notes,
      });
    } else {
      setForm({ ...BLANK_FORM, date: presetDate ?? todayStr() });
    }
  }, [editing, visible, presetDate]);

  const handleSave = () => {
    if (!form.title.trim()) { Alert.alert('', t('calendar.title_required')); return; }
    if (!form.date.match(/^\d{4}-\d{2}-\d{2}$/)) { Alert.alert('', t('calendar.date_required')); return; }
    onSave(form);
  };

  return (
    <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}>
      <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} style={{ flex: 1 }}>
        <ScrollView style={rm.container} contentContainerStyle={{ paddingBottom: 48 }} keyboardShouldPersistTaps="handled">

          {/* Header */}
          <LinearGradient colors={['#F06292', '#F48FB1']} style={rm.header}>
            <TouchableOpacity onPress={onClose} style={rm.closeBtn}>
              <Text style={{ fontSize: 18, color: Colors.white, fontWeight: '800' }}>✕</Text>
            </TouchableOpacity>
            <Text style={rm.headerTitle}>{editing ? t('calendar.edit_reminder') : t('calendar.add_reminder')}</Text>
          </LinearGradient>

          {/* Title */}
          <Text style={rm.label}>{t('calendar.modal_title_label')} *</Text>
          <TextInput style={rm.input} value={form.title} onChangeText={upd('title')}
            placeholder={t('calendar.modal_title_placeholder')} placeholderTextColor="#CCC" />

          {/* Category */}
          <Text style={rm.label}>{t('calendar.modal_category')}</Text>
          <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ marginBottom: 16 }}>
            <View style={{ flexDirection: 'row', gap: 8, paddingHorizontal: 16, paddingBottom: 4 }}>
              {ALL_CATS.map(cat => {
                const sel = form.category === cat;
                return (
                  <TouchableOpacity key={cat}
                    style={[rm.catChip, { backgroundColor: sel ? CAT[cat].color : CAT[cat].bg, borderColor: CAT[cat].color }]}
                    onPress={() => upd('category')(cat)} activeOpacity={0.8}>
                    {CAT[cat].icon}
                    <Text style={[rm.catLabel, { color: sel ? Colors.white : CAT[cat].color }]}>{t(`calendar.${cat}`)}</Text>
                  </TouchableOpacity>
                );
              })}
            </View>
          </ScrollView>

          {/* Date */}
          <Text style={rm.label}>{t('calendar.modal_date')}</Text>
          <TextInput style={rm.input} value={form.date} onChangeText={upd('date')}
            placeholder={t('calendar.modal_date_placeholder')} placeholderTextColor="#CCC"
            keyboardType="numbers-and-punctuation" />

          {/* All Day */}
          <View style={rm.toggleRow}>
            <Text style={rm.toggleLabel}>{t('calendar.modal_all_day')}</Text>
            <Switch value={form.allDay} onValueChange={upd('allDay')}
              trackColor={{ false: '#DDD', true: PINK }} thumbColor="#fff" />
          </View>

          {/* Time */}
          {!form.allDay && (
            <>
              <Text style={rm.label}>{t('calendar.modal_time')}</Text>
              <TextInput style={rm.input} value={form.time} onChangeText={upd('time')}
                placeholder={t('calendar.modal_time_placeholder')} placeholderTextColor="#CCC"
                keyboardType="numbers-and-punctuation" />
            </>
          )}

          {/* Repeat */}
          <Text style={rm.label}>{t('calendar.modal_repeat')}</Text>
          <View style={rm.chipRow}>
            {REPEAT_OPTS.map(o => (
              <TouchableOpacity key={o.key}
                style={[rm.optChip, form.repeatType === o.key && rm.optChipSel]}
                onPress={() => upd('repeatType')(o.key)} activeOpacity={0.8}>
                <Text style={[rm.optLabel, form.repeatType === o.key && { color: Colors.white }]}>{t(o.i18n)}</Text>
              </TouchableOpacity>
            ))}
          </View>

          {/* Notify */}
          <Text style={rm.label}>{t('calendar.modal_notify')}</Text>
          <View style={rm.chipRow}>
            {NOTIFY_OPTS.map(o => (
              <TouchableOpacity key={o.val}
                style={[rm.optChip, form.notifyMinutesBefore === o.val && rm.optChipSel]}
                onPress={() => upd('notifyMinutesBefore')(o.val)} activeOpacity={0.8}>
                <Text style={[rm.optLabel, form.notifyMinutesBefore === o.val && { color: Colors.white }]}>{t(o.i18n)}</Text>
              </TouchableOpacity>
            ))}
          </View>

          {/* Notes */}
          <Text style={rm.label}>{t('calendar.modal_notes')}</Text>
          <TextInput style={[rm.input, { height: 80, textAlignVertical: 'top' }]}
            value={form.notes} onChangeText={upd('notes')} multiline
            placeholder={t('calendar.modal_notes_placeholder')} placeholderTextColor="#CCC" />

          {/* Save */}
          <TouchableOpacity onPress={handleSave} activeOpacity={0.85} style={{ paddingHorizontal: 16, marginTop: 24 }}>
            <LinearGradient colors={['#F06292', '#F48FB1']} style={rm.saveBtn}>
              <Text style={rm.saveTxt}>{t('calendar.save')}</Text>
            </LinearGradient>
          </TouchableOpacity>

          {/* Delete */}
          {editing && !editing.isAutoGenerated && (
            <TouchableOpacity style={rm.deleteBtn} activeOpacity={0.8}
              onPress={() => Alert.alert('', 'Delete this reminder?', [
                { text: t('calendar.cancel'), style: 'cancel' },
                { text: t('calendar.delete'), style: 'destructive', onPress: () => { onDelete(editing.id); onClose(); } },
              ])}>
              <Text style={rm.deleteTxt}>{t('calendar.delete')}</Text>
            </TouchableOpacity>
          )}
        </ScrollView>
      </KeyboardAvoidingView>
    </Modal>
  );
}

const rm = StyleSheet.create({
  container:   { flex: 1, backgroundColor: Colors.background },
  header:      { flexDirection: 'row', alignItems: 'center', padding: 16, paddingTop: 20, gap: 12 },
  closeBtn:    { width: 36, height: 36, borderRadius: 18, backgroundColor: 'rgba(255,255,255,0.3)', alignItems: 'center', justifyContent: 'center' },
  headerTitle: { fontSize: 18, fontWeight: '800', color: Colors.white },
  label:       { fontSize: 13, fontWeight: '700', color: DARK, marginBottom: 6, marginTop: 14, paddingHorizontal: 16 },
  input:       { marginHorizontal: 16, borderRadius: 12, borderWidth: 1, borderColor: Colors.border, backgroundColor: Colors.white, paddingHorizontal: 16, paddingVertical: 12, fontSize: 14, color: DARK, marginBottom: 4, height: 52, fontFamily: 'PlusJakartaSans_400Regular' },
  toggleRow:   { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, marginTop: 8, marginBottom: 4 },
  toggleLabel: { fontSize: 13, fontWeight: '700', color: DARK },
  chipRow:     { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingHorizontal: 16, marginBottom: 4 },
  catChip:     { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1.5 },
  catLabel:    { fontSize: 12, fontWeight: '700' },
  optChip:     { borderRadius: 20, paddingHorizontal: 14, paddingVertical: 8, backgroundColor: '#F5F5F5', borderWidth: 1.5, borderColor: '#E0E0E0' },
  optChipSel:  { backgroundColor: PINK, borderColor: PINK },
  optLabel:    { fontSize: 12, fontWeight: '600', color: GRAY },
  saveBtn:     { borderRadius: 14, height: 52, alignItems: 'center', justifyContent: 'center', shadowColor: PINK, shadowOpacity: 0.3, shadowRadius: 8, elevation: 4 },
  saveTxt:     { color: Colors.white, fontSize: 16, fontWeight: '800' },
  deleteBtn:   { borderRadius: 16, paddingVertical: 14, alignItems: 'center', marginHorizontal: 16, marginTop: 12, borderWidth: 1.5, borderColor: '#E53E3E' },
  deleteTxt:   { color: '#E53E3E', fontSize: 14, fontWeight: '700' },
});

// ─── Notification Settings Panel ──────────────────────────────────────────────

function NotifSettingsPanel({ t }: { t: (k: string) => string }) {
  const { settings, updateSettings } = useReminderStore();
  const [exp, setExp] = useState(false);

  return (
    <View style={ns.card}>
      <TouchableOpacity style={ns.header} onPress={() => setExp(e => !e)} activeOpacity={0.8}>
        <Text style={ns.title}>{t('calendar.settings_title')}</Text>
        <Text style={{ fontSize: 16, color: GRAY }}>{exp ? '▲' : '▼'}</Text>
      </TouchableOpacity>
      {exp && (
        <View style={ns.body}>
          <View style={ns.row}>
            <Text style={ns.rowLabel}>{t('calendar.settings_master')}</Text>
            <Switch value={settings.masterEnabled} onValueChange={v => updateSettings({ masterEnabled: v })}
              trackColor={{ false: '#DDD', true: PINK }} thumbColor="#fff" />
          </View>
          {[
            { key: 'vaccineReminders',    i18n: 'calendar.settings_vaccine' },
            { key: 'checkupReminders',    i18n: 'calendar.settings_checkup' },
            { key: 'feedingReminders',    i18n: 'calendar.settings_feeding' },
            { key: 'medicationReminders', i18n: 'calendar.settings_medication' },
            { key: 'customReminders',     i18n: 'calendar.settings_custom' },
          ].map(({ key, i18n }) => (
            <View key={key} style={[ns.row, { opacity: settings.masterEnabled ? 1 : 0.4 }]}>
              <Text style={ns.rowLabel}>{t(i18n)}</Text>
              <Switch value={(settings as any)[key]} onValueChange={v => updateSettings({ [key]: v })}
                trackColor={{ false: '#DDD', true: PINK }} disabled={!settings.masterEnabled} thumbColor="#fff" />
            </View>
          ))}
          <View style={[ns.row, { marginTop: 8 }]}>
            <Text style={ns.rowLabel}>{t('calendar.settings_quiet')}</Text>
            <Switch value={settings.quietHoursEnabled} onValueChange={v => updateSettings({ quietHoursEnabled: v })}
              trackColor={{ false: '#DDD', true: PINK }} thumbColor="#fff" />
          </View>
          {settings.quietHoursEnabled && (
            <View style={{ flexDirection: 'row', gap: 12, marginTop: 8 }}>
              <View style={{ flex: 1 }}>
                <Text style={[ns.rowLabel, { marginBottom: 4 }]}>{t('calendar.settings_quiet_from')}</Text>
                <TextInput style={ns.timeInput} value={settings.quietHoursStart}
                  onChangeText={v => updateSettings({ quietHoursStart: v })} placeholder="22:00" placeholderTextColor="#BBB" />
              </View>
              <View style={{ flex: 1 }}>
                <Text style={[ns.rowLabel, { marginBottom: 4 }]}>{t('calendar.settings_quiet_to')}</Text>
                <TextInput style={ns.timeInput} value={settings.quietHoursEnd}
                  onChangeText={v => updateSettings({ quietHoursEnd: v })} placeholder="06:00" placeholderTextColor="#BBB" />
              </View>
            </View>
          )}
        </View>
      )}
    </View>
  );
}

const ns = StyleSheet.create({
  card:      { backgroundColor: Colors.surface, borderRadius: 20, marginBottom: 16, shadowColor: Colors.shadowColor, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 16, elevation: 4 },
  header:    { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16 },
  title:     { fontSize: 14, fontWeight: '800', color: DARK },
  body:      { paddingHorizontal: 16, paddingBottom: 16 },
  row:       { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#F5F5F5' },
  rowLabel:  { fontSize: 13, color: GRAY, flex: 1 },
  timeInput: { borderWidth: 1.5, borderColor: '#E0E0E0', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 8, fontSize: 14, color: DARK },
});

// ─── Day Events Bottom Sheet ──────────────────────────────────────────────────

function DayEventsSheet({
  visible, dateStr, events, onClose, onAdd, onEdit, t
}: {
  visible: boolean; dateStr: string; events: CalEvent[];
  onClose: () => void; onAdd: () => void; onEdit: (ev: CalEvent) => void;
  t: (k: string, o?: object) => string;
}) {
  return (
    <Modal visible={visible} animationType="slide" transparent onRequestClose={onClose}>
      <TouchableOpacity style={ds.overlay} onPress={onClose} activeOpacity={1}>
        <View style={ds.sheet}>
          <View style={ds.handle} />
          <View style={ds.sheetHeader}>
            <Text style={ds.sheetTitle}>{t('calendar.events_for_day', { date: fmtDatePH(dateStr) })}</Text>
            <TouchableOpacity onPress={onClose}><Text style={{ fontSize: 18, color: GRAY }}>✕</Text></TouchableOpacity>
          </View>
          <ScrollView style={{ maxHeight: 340 }}>
            {events.length === 0 ? (
              <View style={ds.empty}>
                <Flower2 size={32} strokeWidth={1.5} color={PINK} style={{ marginBottom: 8 }} />
                <Text style={ds.emptyTxt}>{t('calendar.no_events_for_day')}</Text>
              </View>
            ) : (
              <View style={{ paddingHorizontal: 16, paddingBottom: 8 }}>
                {events.map(ev => (
                  <EventCard key={ev.id} ev={ev} onPress={() => {
                    if (ev.source === 'reminder' && ev.reminderId) onEdit(ev);
                  }} />
                ))}
              </View>
            )}
          </ScrollView>
          <TouchableOpacity onPress={onAdd} activeOpacity={0.85} style={{ padding: 16 }}>
            <LinearGradient colors={[Colors.primary, Colors.primaryLight]} style={ds.addBtn}>
              <Text style={ds.addTxt}>{t('calendar.add_event_for_day')}</Text>
            </LinearGradient>
          </TouchableOpacity>
        </View>
      </TouchableOpacity>
    </Modal>
  );
}

const ds = StyleSheet.create({
  overlay:     { flex: 1, backgroundColor: 'rgba(0,0,0,0.35)', justifyContent: 'flex-end' },
  sheet:       { backgroundColor: Colors.background, borderTopLeftRadius: 28, borderTopRightRadius: 28, paddingTop: 12, minHeight: 260 },
  handle:      { width: 48, height: 5, backgroundColor: '#DDD', borderRadius: 3, alignSelf: 'center', marginBottom: 12 },
  sheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, marginBottom: 12 },
  sheetTitle:  { fontSize: 15, fontWeight: '800', color: DARK, flex: 1 },
  empty:       { alignItems: 'center', paddingVertical: 28 },
  emptyTxt:    { fontSize: 14, color: GRAY, fontWeight: '600' },
  addBtn:      { borderRadius: 14, height: 52, alignItems: 'center', justifyContent: 'center' },
  addTxt:      { color: Colors.white, fontSize: 15, fontWeight: '800' },
});

// ─── Main Calendar Screen ─────────────────────────────────────────────────────

export default function CalendarScreen() {
  const { t: tRaw }     = useTranslation();
  // Cast to simple signature so sub-components accept it without TS errors
  const t = tRaw as (k: string, o?: object) => string;
  const { activeChild } = useChildStore();
  const reminderStore   = useReminderStore();
  const vaccineStore    = useVaccineStore();

  const today = new Date();
  const [isLoading,       setIsLoading]       = useState(true);
  const [viewYear,  setViewYear]  = useState(today.getFullYear());
  const [viewMonth, setViewMonth] = useState(today.getMonth());
  const [selDay,    setSelDay]    = useState<number | null>(null);
  const [modalVisible,    setModalVisible]    = useState(false);
  const [editingReminder, setEditingReminder] = useState<Reminder | null>(null);
  const [presetDate,      setPresetDate]      = useState<string | undefined>(undefined);
  const [daySheetVisible, setDaySheetVisible] = useState(false);
  const [filterCat, setFilterCat] = useState<ReminderCategory | 'all'>('all');

  // ── Mount-time loading spinner ──────────────────────────────────────────────
  useEffect(() => {
    const timer = setTimeout(() => setIsLoading(false), 300);
    return () => clearTimeout(timer);
  }, []);

  // ── Auto-generate PPS + GP on load ─────────────────────────────────────────
  useEffect(() => {
    if (!activeChild?.id || !activeChild.birthday) return;
    const nickname = getChildDisplayName(activeChild);
    reminderStore.autoGeneratePPS(activeChild.id, activeChild.birthday, nickname);
    reminderStore.autoGenerateGP(activeChild.id, today.getFullYear());
  }, [activeChild?.id]);

  // ── Build unified CalEvent list ─────────────────────────────────────────────
  const allEvents = useMemo<CalEvent[]>(() => {
    if (!activeChild?.id) return [];

    const remEvents: CalEvent[] = reminderStore.reminders
      .filter(r => r.childId === activeChild.id && r.isActive)
      .map(r => ({
        id: r.id, title: r.title,
        date: r.scheduledAt.split('T')[0],
        time: r.allDay ? undefined : r.scheduledAt.split('T')[1]?.substring(0, 5),
        category: r.category, allDay: r.allDay,
        notes: r.notes || undefined,
        source: 'reminder' as const, reminderId: r.id,
        isAutoGenerated: r.isAutoGenerated,
      }));

    const vaxEvents: CalEvent[] = vaccineStore.getRecords(activeChild.id)
      .filter(r => r.reminderEnabled && r.reminderDate && r.status !== 'given')
      .map(r => ({
        id: 'vax-' + r.id,
        title: `${r.nameEN} reminder`,
        date: r.reminderDate as string,   // safe: filtered above
        time: '09:00',
        category: 'vaccine' as ReminderCategory,
        allDay: false,
        notes: t('calendar.vaccine_reminder_note'),
        source: 'vaccine' as const,
        isAutoGenerated: true,
      }));

    return [...remEvents, ...vaxEvents]
      .sort((a, b) => a.date.localeCompare(b.date) || (a.time ?? '').localeCompare(b.time ?? ''));
  }, [reminderStore.reminders, activeChild?.id, vaccineStore.records]);

  const filteredEvents = useMemo(() =>
    filterCat === 'all' ? allEvents : allEvents.filter(e => e.category === filterCat),
    [allEvents, filterCat]);

  // ── Dot map for calendar ────────────────────────────────────────────────────
  const dotMap = useMemo(() => {
    const map = new Map<number, ReminderCategory[]>();
    for (const ev of filteredEvents) {
      const d = new Date(ev.date);
      if (d.getFullYear() === viewYear && d.getMonth() === viewMonth) {
        const day = d.getDate();
        if (!map.has(day)) map.set(day, []);
        const cats = map.get(day)!;
        if (!cats.includes(ev.category)) cats.push(ev.category);
      }
    }
    return map;
  }, [filteredEvents, viewYear, viewMonth]);

  // ── Selected day events ─────────────────────────────────────────────────────
  const selectedDateStr = selDay != null ? toDateStr(viewYear, viewMonth, selDay) : '';
  const selectedDayEvents = useMemo(() =>
    selDay != null ? filteredEvents.filter(e => e.date === selectedDateStr) : [],
    [filteredEvents, selectedDateStr]);

  // ── Upcoming events (60 days) ───────────────────────────────────────────────
  const upcomingEvents = useMemo(() => {
    const now = new Date(); now.setHours(0,0,0,0);
    const end = new Date(now); end.setDate(end.getDate() + 60);
    return filteredEvents.filter(e => {
      const d = new Date(e.date); return d >= now && d <= end;
    });
  }, [filteredEvents]);

  // ── Month nav ───────────────────────────────────────────────────────────────
  const prevMonth = () => {
    if (viewMonth === 0) { setViewYear(y => y-1); setViewMonth(11); }
    else setViewMonth(m => m-1);
    setSelDay(null);
  };
  const nextMonth = () => {
    if (viewMonth === 11) { setViewYear(y => y+1); setViewMonth(0); }
    else setViewMonth(m => m+1);
    setSelDay(null);
  };

  // ── Modal handlers ──────────────────────────────────────────────────────────
  const openAdd = (date?: string) => {
    setEditingReminder(null);
    setPresetDate(date);
    setDaySheetVisible(false);
    setModalVisible(true);
  };
  const openEdit = (ev: CalEvent) => {
    if (ev.source === 'vaccine' || !ev.reminderId) return;
    const rem = reminderStore.reminders.find(r => r.id === ev.reminderId) ?? null;
    setEditingReminder(rem);
    setDaySheetVisible(false);
    setModalVisible(true);
  };
  const handleSave = (form: ReminderForm) => {
    if (!activeChild?.id) return;
    const scheduledAt = (form.allDay ? form.date + 'T00:00' : form.date + 'T' + (form.time || '09:00'));
    if (editingReminder) {
      reminderStore.updateReminder(editingReminder.id, {
        title: form.title, category: form.category, scheduledAt,
        allDay: form.allDay, repeatType: form.repeatType,
        notifyMinutesBefore: form.notifyMinutesBefore, notes: form.notes,
      });
    } else {
      reminderStore.addReminder({
        childId: activeChild.id, title: form.title, category: form.category,
        scheduledAt, allDay: form.allDay, repeatType: form.repeatType,
        notifyMinutesBefore: form.notifyMinutesBefore, notes: form.notes,
        isActive: true, isAutoGenerated: false,
      });
    }
    setModalVisible(false);
    setEditingReminder(null);
  };

  // ── Loading guard ────────────────────────────────────────────────────────────
  if (isLoading) {
    return (
      <View style={{ flex: 1, backgroundColor: BG }}>
        {/* Calendar placeholder */}
        <View style={{ margin: 16, borderRadius: 20, backgroundColor: '#fff', padding: 16,
          shadowColor: Colors.shadowColor, shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.08, shadowRadius: 16, elevation: 4 }}>
          <View style={{ height: 24, width: '40%', borderRadius: 8, backgroundColor: Colors.divider, marginBottom: 14 }} />
          <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
            {Array.from({ length: 7 }).map((_, i) => (
              <View key={i} style={{ width: 32, height: 32, borderRadius: 16, backgroundColor: Colors.divider }} />
            ))}
          </View>
          <View style={{ marginTop: 12, gap: 8 }}>
            {Array.from({ length: 5 }).map((_, i) => (
              <View key={i} style={{ flexDirection: 'row', gap: 6 }}>
                {Array.from({ length: 7 }).map((_, j) => (
                  <View key={j} style={{ width: 32, height: 32, borderRadius: 16, backgroundColor: Colors.divider, opacity: 0.5 + (j % 3) * 0.2 }} />
                ))}
              </View>
            ))}
          </View>
        </View>
        {/* Event rows */}
        <SkeletonList count={4} variant="row" />
      </View>
    );
  }

  // ── No child guard ──────────────────────────────────────────────────────────
  if (!activeChild) {
    return (
      <View style={{ flex: 1, backgroundColor: BG, alignItems: 'center', justifyContent: 'center', padding: 32 }}>
        <CalendarIcon size={48} strokeWidth={1.5} color={PINK} style={{ marginBottom: 16 }} />
        <Text style={{ fontSize: 18, fontWeight: '800', color: DARK, textAlign: 'center', marginBottom: 8 }}>
          {t('calendar.empty_state_title')}
        </Text>
        <Text style={{ fontSize: 14, color: GRAY, textAlign: 'center', lineHeight: 22 }}>
          {t('calendar.empty_state_sub')}
        </Text>
      </View>
    );
  }

  // ── Group upcoming by date label ────────────────────────────────────────────
  const upcomingGrouped: { label: string; date: string; events: CalEvent[] }[] = [];
  const seenDates = new Set<string>();
  for (const ev of upcomingEvents) {
    if (!seenDates.has(ev.date)) {
      seenDates.add(ev.date);
      upcomingGrouped.push({
        label: relativeDayLabel(ev.date, t), date: ev.date,
        events: upcomingEvents.filter(e => e.date === ev.date),
      });
    }
  }

  return (
    <View style={{ flex: 1, backgroundColor: BG }}>
      <ScrollView contentContainerStyle={sc.content} showsVerticalScrollIndicator={false}>

        {/* Weekly summary */}
        <WeeklySummaryBar events={allEvents} t={t} />

        {/* Monthly calendar grid */}
        <MonthGrid
          year={viewYear} month={viewMonth} selectedDay={selDay}
          onDayPress={d => { setSelDay(d); setDaySheetVisible(true); }}
          dotMap={dotMap} onPrev={prevMonth} onNext={nextMonth}
        />

        {/* Category legend */}
        <Text style={sc.sectionTitle}>{t('calendar.legend_title')}</Text>
        <CategoryLegend t={t} />

        {/* Category filter chips */}
        <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ marginBottom: 16 }}>
          <View style={{ flexDirection: 'row', gap: 8, paddingHorizontal: 2, paddingBottom: 4 }}>
            {(['all', ...ALL_CATS] as (ReminderCategory | 'all')[]).map(cat => {
              const sel = filterCat === cat;
              const cfg = cat === 'all' ? { color: PINK, bg: Colors.softPink, icon: <CalendarDays size={13} strokeWidth={1.5} color={PINK} /> } : CAT[cat];
              return (
                <TouchableOpacity key={cat}
                  style={[fc.chip, { backgroundColor: sel ? cfg.color : Colors.white, borderColor: cfg.color }]}
                  onPress={() => setFilterCat(cat)} activeOpacity={0.8}>
                  {cfg.icon}
                  <Text style={[fc.label, { color: sel ? Colors.white : cfg.color }]}>
                    {cat === 'all' ? t('calendar.filter_all') : t(`calendar.${cat}`)}
                  </Text>
                </TouchableOpacity>
              );
            })}
          </View>
        </ScrollView>

        {/* Upcoming events */}
        <View style={sc.sectionRow}>
          <Text style={sc.sectionTitle}>{t('calendar.upcoming_section')}</Text>
          <Text style={sc.sectionSub}>{t('calendar.upcoming_subtitle', { days: 60 })}</Text>
        </View>

        {upcomingGrouped.length === 0 ? (
          <View style={sc.emptyBox}>
            <Flower2 size={36} strokeWidth={1.5} color={PINK} style={{ marginBottom: 8 }} />
            <Text style={sc.emptyTxt}>{t('calendar.no_upcoming')}</Text>
          </View>
        ) : (
          upcomingGrouped.map(grp => (
            <View key={grp.date} style={{ marginBottom: 8 }}>
              <View style={sc.dateLabelRow}>
                <Text style={sc.dateLabel}>{grp.label}</Text>
                <Text style={sc.dateNum}>{fmtDatePH(grp.date)}</Text>
              </View>
              {grp.events.map(ev => (
                <EventCard key={ev.id} ev={ev}
                  onPress={() => { if (ev.source === 'reminder' && ev.reminderId) openEdit(ev); }} />
              ))}
            </View>
          ))
        )}

        {/* Notification settings */}
        <NotifSettingsPanel t={t} />

        {/* Find BHS / RHU */}
        <TouchableOpacity activeOpacity={0.85}>
          <LinearGradient colors={[Colors.blue, '#4A9DE8']} style={sc.bhsBtn}>
            <Text style={sc.bhsTxt}>{t('calendar.find_bhs')}</Text>
          </LinearGradient>
        </TouchableOpacity>

        <View style={{ height: 24 }} />
      </ScrollView>

      {/* FAB */}
      <TouchableOpacity style={sc.fab} onPress={() => openAdd()} activeOpacity={0.85}>
        <LinearGradient colors={['#F06292', Colors.primaryPink]} style={sc.fabGrad}>
          <Text style={{ fontSize: 28, color: Colors.white, lineHeight: 32 }}>+</Text>
        </LinearGradient>
      </TouchableOpacity>

      {/* Day sheet */}
      <DayEventsSheet
        visible={daySheetVisible && selDay != null}
        dateStr={selectedDateStr} events={selectedDayEvents}
        onClose={() => setDaySheetVisible(false)}
        onAdd={() => openAdd(selectedDateStr)}
        onEdit={openEdit} t={t}
      />

      {/* Add/Edit modal */}
      <ReminderModal
        visible={modalVisible} editing={editingReminder}
        childId={activeChild.id} presetDate={presetDate}
        onClose={() => { setModalVisible(false); setEditingReminder(null); }}
        onSave={handleSave}
        onDelete={id => { reminderStore.deleteReminder(id); }}
        t={t}
      />
    </View>
  );
}

const fc = StyleSheet.create({
  chip:  { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 7, borderWidth: 1.5 },
  label: { fontSize: 11, fontWeight: '700' },
});
const sc = StyleSheet.create({
  content:      { padding: 16, paddingBottom: 100 },
  sectionRow:   { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  sectionTitle: { fontSize: 13, fontWeight: '800', color: PINK, textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 8 },
  sectionSub:   { fontSize: 11, color: GRAY },
  dateLabelRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 6 },
  dateLabel:    { fontSize: 12, fontWeight: '800', color: PINK, backgroundColor: Colors.softPink, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 4 },
  dateNum:      { fontSize: 11, color: GRAY },
  emptyBox:     { alignItems: 'center', backgroundColor: Colors.white, borderRadius: 18, padding: 32, marginBottom: 16 },
  emptyTxt:     { fontSize: 14, color: GRAY, fontWeight: '600' },
  bhsBtn:       { borderRadius: 16, paddingVertical: 16, alignItems: 'center', marginBottom: 12, shadowColor: Colors.blue, shadowOpacity: 0.25, shadowRadius: 8, elevation: 4 },
  bhsTxt:       { color: Colors.white, fontSize: 15, fontWeight: '800' },
  fab:          { position: 'absolute', bottom: 88, right: 20, shadowColor: PINK, shadowOpacity: 0.4, shadowRadius: 12, elevation: 8 },
  fabGrad:      { width: 58, height: 58, borderRadius: 29, alignItems: 'center', justifyContent: 'center' },
});
